version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  pack-test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: pack
          command: npm pack
      - run:
          name: test
          command: npm test
workflows:
  pack-test:
    jobs:
      - pack-test
