version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  pack:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm pack start
workflows:
  pack_my_app:
    jobs:
      - pack
